import type { Metadata } from "next";
import { Geist, Geist_Mono, Anton, Bebas_Neue } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/Navbar";
import Footer from "@/components/Footer";
// import Ribbon from "@/components/Ribbon";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const anton = Anton({
	subsets: ["latin"],
	weight: "400", // Anton only comes in 400 weight
	variable: "--font-anton",
	display: "swap",
});
const bebas = Bebas_Neue({
	subsets: ["latin"],
	weight: "400", // Only 400 is available for Bebas Neue
	variable: "--font-bebas",
	display: "swap",
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Evergreen",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} ${bebas.variable} antialiased`}
			>
				{/* <Ribbon /> */}
				<NavBar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
