import type { Metadata } from "next";
import { Geist, Geist_Mono, Anton, Bebas_Neue, Roboto } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/Navbar";
import Footer from "@/components/Footer";
// import Ribbon from "@/components/Ribbon";
import { Toaster } from "@/components/ui/sonner";

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin"],
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const anton = Anton({
	subsets: ["latin"],
	weight: "400", // Anton only comes in 400 weight
	variable: "--font-anton",
	display: "swap",
});
const bebas = Bebas_Neue({
	subsets: ["latin"],
	weight: "400", // Only 400 is available for Bebas Neue
	variable: "--font-bebas",
	display: "swap",
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Evergreenry",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.ico",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} ${bebas.variable} ${roboto.variable} antialiased bg-gradient-to-br from-green-50 via-white to-green-50/40`}
			>
				{/* <Ribbon /> */}
				<NavBar />
				{children}
				<Toaster />
				<Footer />
			</body>
		</html>
	);
}
